Remove patch process
thehyve/cbioportal-docker pull request #29
Opened 2018-01-26 16:25 UTC by sandertan

- Remove patch process of portal.properties
- Update documentation accordingly
- Remove some MSK and TCGA specific information
- Add portal.properties.EXAMPLE of current version of cBioPortal

2018-02-20 12:04 UTC, pieterlukasse requested changes
Really nice :+1: 
There is 1 small issue I commented on regarding log4j.properties

2018-02-20 12:04 UTC, pieterlukasse commented on Dockerfile
> +RUN cp src/main/resources/log4j.properties.EXAMPLE src/main/resources/log4j.properties \
this makes it harder to overwrite the log4j settings with an external file. Please add `COPY` command above, similar to what was done for portal.properties.

2018-02-20 12:04 UTC, pieterlukasse commented on docs/adjusting_portal.properties_configuration.md
> +To modify the configuration for your own cBioPortal instance, please add modifications to `portal.properties`. This file already contains several modifications for this Docker setup.
and log4j.properties.

2018-02-20 13:01 UTC, pieterlukasse approved these changes
great! Happy to see this configuration part simplified now!

2018-02-20 13:34 UTC, sandertan commented
Rebased and add `Update portal.properties(.EXAMPLE) to v1.11.2`-commit

2018-02-20 14:51 UTC, fedde-s commented
Would this make it easier to document the steps to adjust your config to the options supported by another branch/release, somewhere in [this file](https://github.com/thehyve/cbioportal-docker/blob/3ad3f4281761e4121c0cf690d554bc09ea3886d0/docs/adjusting_Dockerfile_configuration.md#build-an-image-based-on-a-different-branch)?

2018-02-20 14:52 UTC, fedde-s commented
It does become easier to have such mismatches go completely unnoticed, I imagine.

2018-02-21 09:35 UTC, fedde-s commented
Nice, merging those two config docs makes them a lot easier to find.

2018-02-21 09:36 UTC, fedde-s commented
@sandertan, would you like me to release this or are you still tweaking something?

2018-02-21 10:33 UTC, sandertan commented
@fedde-s go ahead!

2018-02-21 10:37 UTC, sandertan commented
@fedde-s small naming suggestion: Renaming `cbioportal-image` to `cbioportal`.

2018-02-21 10:41 UTC, fedde-s commented
I included the word ‘image’ on purpose, as I imagined it might be difficult for people who've never used Docker before to know whether they're dealing with an image or a container if they have the same name. Not sure if there's a better solution for that.

2018-02-21 10:53 UTC, sandertan commented
Indeed, in this case, it might be best to help the new people!

2018-02-22 11:29 UTC, merged