Update adjusting_configuration.md
thehyve/cbioportal-docker pull request #6
Opened 2016-10-05 13:30 UTC by oplantalech

@fedde-s I updated the documentation with more detailed steps.

2016-10-05 13:34 UTC, fedde-s commented
I see that the link to the documentation of skin properties is still empty, it should point to https://github.com/cBioPortal/cbioportal/blob/master/docs/Customizing-your-instance-of-cBioPortal.md.

2016-10-05 13:36 UTC, oplantalech commented
@fedde-s Done.

2016-10-05 14:05 UTC, fedde-s requested changes

2016-10-05 14:05 UTC, fedde-s commented on adjusting_configuration.md
> +1- If you have built a cBioPortal Docker image before (like the step 3 of [Readme](https://github.com/thehyve/cbioportal-docker/blob/master/README.md)), you would find the files `portal.properties` i
This is incorrect. You have to copy them out of the container using `docker cp`.

2016-10-05 14:05 UTC, fedde-s commented on adjusting_configuration.md
> +1- If you have built a cBioPortal Docker image before (like the step 3 of [Readme](https://github.com/thehyve/cbioportal-docker/blob/master/README.md)), you would find the files `portal.properties` i
Could you clarify the reference to `step 2'? There are two steps numbered 2 before the one you probably mean.

2016-10-05 14:05 UTC, fedde-s commented on adjusting_configuration.md
> +1- If you have built a cBioPortal Docker image before (like the step 3 of [Readme](https://github.com/thehyve/cbioportal-docker/blob/master/README.md)), you would find the files `portal.properties` i
Could you use full stops instead of hyphens in the numbering? That way GitHub's [Markdown](https://guides.github.com/features/mastering-markdown/#syntax) parser will recognise it as a numbered list.

2016-10-05 14:05 UTC, fedde-s commented on adjusting_configuration.md
> +1. Create a generic cBioPortal Docker image by following the step 3 of [Readme](https://github.com/thehyve/cbioportal-docker/blob/master/README.md) and go back to step 1.
I think this line can simply be removed, as it is already suggested in the step it refers back to.

2016-10-05 15:09 UTC, oplantalech commented on adjusting_configuration.md
> +
I think all instructions are correct now but I don't really know how to solve this command, since I cannot figure how the cbioportal container is structured.

2016-10-25 10:26 UTC, pieterlukasse commented
I would only document option 2. And instead of writing things out like "The file must be saved twice in the directory where you have downloaded the ..." , just write the commands (like wget).

2016-10-25 16:12 UTC, fedde-s commented
There are two advantages to building a default image and copying out the files: the Dockerfile will download the right release (which one is &lsquo;your cBioPortal version&rsquo; as these instructions mention is not otherwise documented), and it will run the included patch with my alternative defaults applicable to non-MSK instances. However, it also needlessly compiles cBioPortal an extra time.

2016-10-25 16:31 UTC, fedde-s commented on adjusting_configuration.md
> +If you have built a cBioPortal Docker image before (like the step 3 of [Readme](https://github.com/thehyve/cbioportal-docker/blob/master/README.md)), you have to retrieve the files `portal.properties
Could you replace the comma after &lsquo;these Docker container&rsquo; (probably a typo too) by a full stop? Currently it looks like that's a step you need to figure out before you reading the rest of the sentence.

2016-10-26 08:25 UTC, oplantalech commented
So I made the changes, you can take a look now and see if it is ok or should I simplify it more

2016-10-26 10:10 UTC, oplantalech commented
@pieterlukasse I made the changes, but I kept them in the same document since this would have to be updated/removed soon. I think the Dockerfile part looks a bit silly

2016-10-26 10:21 UTC, fedde-s submitted a review, later dismissed

2016-10-26 10:22 UTC, fedde-s commented
I still don't like some of the phrasing, but close enough. It's no longer too convoluted, and certainly better than having no documentation at all.

2016-10-26 10:23 UTC, fedde-s commented
One thing is missing though: no part of the documentation refers to this file.

2017-02-13 20:22 UTC, pieterlukasse requested changes

2017-02-13 20:22 UTC, pieterlukasse commented on adjusting_configuration.md
> +# Run image with changes in Dockerfile or properties
could you split up in two documentation files? One just about changing properties, and one just about eventual changes to the Dockerfile (and maybe give an example for this one).

2017-02-13 20:22 UTC, pieterlukasse commented on adjusting_configuration.md
> +docker build -t custom/cbioportal .
please use same naming as in the other documentation. I believe we call it `cbioportal-image` now

2017-02-14 10:07 UTC, oplantalech commented
@pieterlukasse I update the PR with your comments. We were discussing with @fedde-s that if somebody wants to create an image not based on the current cBioPortal version (default), a parameter could be added in the command `docker build -t cbioportal-image .`. This would make the file `adjusting_Dockerfile_configuration.md` useless.

2017-02-14 10:32 UTC, pieterlukasse approved these changes

2017-02-14 10:34 UTC, pieterlukasse commented
thanks @oplantalech. Regarding `adjusting_Dockerfile_configuration.md` being useless, I disagree. In most deployments we end up changing not only the branch that is taken but also make small patches, copy in extra files (e.g. .jks file for SAML auth), etc.

2017-02-14 10:42 UTC, fedde-s commented
Yes, it makes sense sense to document more extensive adjustments to the build process at some point. More examples of files are extra CSS and images (logos). But I think that would work in a future iteration, this changeset is already an improvement over the current lack of documentation, even with my doubts about `wget`ing the example config file from GitHub separately from the rest of the code.

2017-02-14 10:43 UTC, fedde-s commented
@oplantalech, would you like to rewrite the commit history  before I merge it?

2017-03-10 17:09 UTC, oplantalech commented
@fedde-s the commits are already squashed, so the PR is ready to merge

2017-03-17 08:13 UTC, fedde-s commented
@oplantalech, could you resolve the conflict?

2017-03-20 09:30 UTC, oplantalech commented
@fedde-s Done.

2017-03-20 10:01 UTC, fedde-s commented on README.md
> -If you want to change any variable defined in portal.properties, have a look [here](adjusting_portal.properties_configuration.md). If you want to build an image based on a different branch, you can r
Shouldn't README.md point to the new pages of documentation?

2017-03-20 10:02 UTC, oplantalech commented on README.md
> -If you want to change any variable defined in portal.properties, have a look [here](adjusting_portal.properties_configuration.md). If you want to build an image based on a different branch, you can r
Thanks for pointing it out. It was a mistake when solving the merging conflict. I will introduce this part again!

2017-03-20 10:18 UTC, fedde-s commented
I rebased on master to fix the merge conflict as you did, but without the merge and fixup commits.

2017-03-20 10:19 UTC, merged